:toc: right
:toclevels: 2
:pagenums:
:sectnums: y
:sectnumlevels: 8
:imagesdir: ./figures
:icons: font
:data-uri:
:linkcss:
:pdf-page-size: a4
:doctype: book
= MML 4.1.2

[[introduction]]
== Introduction

MML has been developed from 1995 as a standard for the exchange of medical data. The first version used SGML as a formalism, and XML was adopted from the second version. Clinical information modules have been developed to express use cases in clinical domain, and related tables have been . In 2004, MML was harmonized with the HL7 CDA rel 1 format as an attempt at improving interoperability with international standards and pulished as MML version 3.

Beginning from 2007, we have researched harmonizing with MML with the ISO13606 standard that is expected to be the next-generation EHR standard. Based on this rearch, vital signs module and flowsheet module were designed in 2013, and a prescription module and injection module were published in 2015.

In addition to these achievements, we decided to release MML version 4 including the hemodialysis module, which was developed by a hemodialysis SIG, and changed the schema definition language from DTD to  W3C XML Schema 1.1.

NOTE: This document and the XML schema were officially approved as MML version 4 standard on the board, but they are still in the bug fix phase, updates are inevitable.

[[update_policy]]
== Updating policy for MML version 4 release
As described above, the largest change in this revision is adopting W3C XML Schema 1.1. This change intended to improve convenience for developers to implement this MML standard, because XML Schema can strictly define the data types and data structures, and a broad range of related tools are available.

Moreover it was decided to simplify the structure by eliminating the HL7 CDA-related tags that had become redundant. However it was decided to keep the same namespace and tag names, and to keep the XPath structure that is semantically equivalent in order to reduce the costs involved with the version upgrade.

Shift JIS was the official character encoding up to Ver. 3, but we adopted UTF-8 in Ver. 4. This improves convenience of implementation as well as interoperabiltiy with other standards.

It was also decided to officially add the following modules which had previously been published as Plan B.

. Hemodialysis module
. Vital signs module
. Flowsheet module
. Prescription module
. Injection module

The Data Exchange Specification that had been defined in MML 2.3 was obsoleted.


[[intelectual_property]]
==  Intellectual property

All of the copyrights in this specification belong to the MedXML Consortium Non-Profit Organization. Thus, all uses of the specification shall comply with the policies of the MedXML Consortium Non-Profit Organization.

.Policy of the MedXML Consortium Non-Profit Organization in relation to products created
----
In principle, a product that is created by this Consortium shall be made public on the Internet and treated as being in the public domain. Thus, both consortium members and non-members can make use of such products for commercial or academic activities. While using such products, however, the user shall be obligated to report to the Consortium and to clearly indicate that the product of the Consortium is being used in a product, written work, or for other purposes in compliance with copyrights and preferences.
----

include::references_e.adoc[]

include::overview_e.adoc[]

include::principle_e.adoc[]

include::common_components.adoc[]

include::header.adoc[]

include::docinfo.adoc[]

include::content_modules.adoc[]
