:Author: Shinji KOBAYASHI
:Email: skoba@moss.gr.jp
:toc: right
:toclevels: 2
:pagenums:
:sectnums: y
:sectnumlevels: 8
:sectoffset: 6
:imagesdir: ./figures
:linkcss:

== Basic policies

toc::[]

=== Version control of modules and namespace declaration
From this version 4 release, namespace declaration is separated with each version.

Before this release, the version of module was described at the end of namespace declaration.

For example, the following is the name space declaration of test history information module.

[source, xml]
----
 xmlns:mmlLb="http://www.medxml.net/MML/ContentModule/test/1.0"
----
This declaration shows that the version of laboratory test history module is 1.0, even if this modules was involved in either version MML Ver 3.0 or version MML Ver 2.3.

To clarify the version of MML, the version of MML is described after the URL of MedXML consortium as following.
[source, xml]
-----
 xmlns:mml="http://www.medxml.net/MML/v4"
-----

Version of each module is described the end of URL. This version will be changed after updates of module schema.

[source, xml]
-----
 xmlns:mmlLb="http://www.medxml.net/MML/v4/ContentModule/test/1.0"
-----
The modules and namespace declarations that are used with MML Version 4.0 are the following.

Structure module of MmlHeader and docInfo::
	xmlns:mml ="http://www.medxml.net/MML/v4/base/1.0"
Patient information module::
	xmlns:mmlPi ="http://www.medxml.net/MML/v4/ContentModule/PatientInfo/1.0"
Health insurance information module::
	xmlns:mmlHi ="http://www.medxml.net/MML/v4/ContentModule/HealthInsurance/1.1"
Diagnosis record information module::
	xmlns:mmlRd ="http://www.medxml.net/MML/v4/ContentModule/RegisteredDiagnosis/1.0"
Lifestyle information module::
	xmlns:mmlLs ="http://www.medxml.net/MML/v4/ContentModule/Lifestyle/1.0"
Basic clinical information module::
	xmlns:mmlBc ="http://www.medxml.net/MML/v4/ContentModule/BaseClinic/1.0"
Initial-consultation specific information::
	xmlns:mmlFcl ="http://www.medxml.net/MML/v4/ContentModule/FirstClinic/1.0"
Progress course information module::
	xmlns:mmlPc ="http://www.medxml.net/MML/v4/ContentModule/ProgressCourse/1.0"
Surgery record information module::
	xmlns:mmlSg ="http://www.medxml.net/MML/v4/ContentModule/Surgery/1.0"
Clinical summary information module::
	xmlns:mmlSm ="http://www.medxml.net/MML/v4/ContentModule/Summary/1.0":
Test history information module::
	xmlns:mmlLb="http://www.medxml.net/MML/v4/ContentModule/Test/1.0"
Report information module::
	xmlns:mmlRp="http://www.medxml.net/MML/v4/ContentModule/Report/1.0"
Referral module::
	xmlns:mmlRe="http://www.medxml.net/MML/v4/ContentModule/Referral/1.0"
Vital signs module::
	xmlns:mmlVs="http://www.medxml.net/MML/v4/ContentModule/VitalSign/1.0"
Flow sheet module::
	xmlns:mmlFs="http://www.medxml.net/MML/v4/ContentModule/FlowSheet/1.0"
Prescription module::
	xmlns:mmlFs="http://www.medxml.net/MML/v4/ContentModule/Prescription/1.0"
Injection record module::
	xmlns:mmlFs="http://www.medxml.net/MML/v4/ContentModule/Injection/1.0"
Hemodialysis module::
	xmlns:mmlHd="http://www.medxml.net/MML/v4/ContentModule/Hemodialysis/1.0"

=== Data definitions of MML

==== Types and definitions of time
MML defines various types of time according to the granularity and its features. These are listed below.

Indicates the time when the MML instance was created. It is expected that this will be input automatically as a time stamp when the MML creation process is executed. Therefore in principle it is unrelated to the time of the information that is recorded in the MML instance. Even if the information dates from 10 years earlier, because the MML instance was created today, the time when the instance was created will be recorded.

.Time expression in MML
1 createDate (as an attribute of Mml in MML basic structure)::
Indicates the time when the MML instance was created. It is expected that this will be input automatically as a time stamp when the MML creation process is executed. Therefore it is does not indicate the time of the information recorded in the MML instance in principle. Even if the recorded dates in MML instance was from 10 years earlier and the MML instance was created today,  the createDate should be the time of today when the instance was created.
2 start (as an attribute of scopePeriod in MML basic structure)::
This is the start date of the period for all of the information recorded in the MML instance. When there are multiple MmlModuleItem, this should be the start date of the entire period which includes all of the MmlModuleItem.
3 end (as an attribute scopePeriod of in MML basic structure)::
This is the end date of the period for all of the information recorded in the MML instance. When there are multiple MmlModuleItem, this should be the end date of the entire period which includes all of the MmlModuleItem.
4 confirmDate (as an attribute of MML basic structure)::
This is the date when information in the content of this document was finally fixed. Ordinarily this corresponds to the date when the medical record was electronically recorded. A confirmation date should be the date the event occurred and was recorded in a document. If the document about the events that happened before some days, the confirmDate should be the date when the document was recorded. In an MML document, it should be confirmed in the document content to determine the accurate date when the event happened.  Although there are cases when an event date is explicitly recorded as an element in a document, there are also cases when it is necessary to judge from the context or other information. This is unavoidable due to the way of current medical records operation.
5 start(as an attribute of confirmDate, MML basic structure)::
If the description of a content shows information across multiple dates (for example a summary), this records the start date of the period covered with the described information in the document. Unlike scopePeriod in (2) above which is the period that covers the entire MML instance, this start means the start of period of the a MmlModuleItem.
6 end (as an attribute of confirmDate, MML basic structure)::
In the same way as above, if the description of a content shows information across multiple dates, this records the end date of the period of the a MmlModuleItem.
7 mmlHi:startDate (as an attribute of Health insurance information module)::
This is the date on which the health insurance was issued. Because this date is unrelated to medical events, it is not subject to (2), (3), (5), and (6) above.
8 mmlHi:expiredDate(as an attribute of Health insurance informationmodule )::
This is the health insurance expiration date. Because this date also is unrelated to medical events, it is not subject to (2), (3), (5), and (6) above.
mmlRd:startDate (as an attribute of Diagnosis record information module)::
This date is not the date when a patient got the disease at first. It is the start date for use in insurance claims, and because it is unrelated to medical events, it is not subject to (2), (3), (5), and (6) above.
9 mmlRd:endDate(as an attribute of Diagnosis record information module)::
This date is not the date when the disease was cured. It is the end date for use in insurance claims. Because it is unrelated to medical events, it is not subject to (2), (3), (5), and (6) above.
10 mmlRd:firstEncounterDate(as an attribute of Diagnosis record information module)::
This is the first visit date, and is the date of the first date to start health insurance record. Because this event is unrelated to the symptoms and treatment of the illness itself, this date is also not subject to (2), (3), (5), and (6) above.
11 mmlSg:date (Surgery record information)::
This is the date that surgical operation was performed (date of event occurrence). It is not the date that this module was recorded. It is recorded as a (4) confirmDate MML basic structure. Because there are cases when the recording is not completed on the surgery date, mmlSg:date and confirmDate may not always be the same.
12 mmlSm:start (Clinical summary information, mmlSm:serviceHistory attribute)::
This is the start date for the period covered by the summary. It is usually the same value as the start attribute of the confirmDate in MML basic structure.
13 mmlSm:end (Clinical summary information, mmlSm:serviceHistory attribute)::
This is the end date for the period covered by the summary. It is usually the same value as the end attribute of the confirmDate in MML basic structure.

==== Granularity of elements
Element granularity is a common issue. For example, patient name is whether the patient name is unstructured and handled as a single element, or divided into elements such as last name and first name. As usual, it is preferable that information be prescribed using a fine-grain data model. However it is also necessary to consider that data will be collected by existing information systems. MML takes the step of allowing elements with different granularity to be selected, in order to prevent data degradation caused by mismatching granularity of data collected from different information systems.
Concrete examples are shown below.
==========================
. The address expression format: unstructured address (mmlAd:full) and tructured format (mmlAd:prefecture, mmlAd:city, mmlAd:town, mmlAd:homeNumber)
. The name expression format: unstructured name expression (mmlNm:fullname) and structured format (mmNm:family, mmlNm:given, mmlNm: middle)
. The diagnosis record information: unstructured diagnosis (mmlRd:diagnosis) and structured format (mmlRd:diagnosisContents)
. The initial-consultation-specific information: free text style expression (mmlFcl:freeNotes), and structured with time and event expressions (mmlFcl:pastHistoryItem)

. The progress course information: free text style expression (mmlPc:FreeExpression) and structured expression (mmlPc:structuredExpression)

. The subjective information in the progress course module: free text style expression (mmlPc:freeNotes), and structured by time and event expressions (mmlPc:subjectiveItem)

. The surgery record information, a full expression of a series of surgery procedures (mmlSg:operation) and separated elements expression (mmlSg:operationElement)
==========================
Even if an MML instance was generated accurately, the interchangeability between the MML instance and local database schema depends largely on the information granularity of the local database. If there was a mismatch in granularity, you should be careful in order to prevent data loss. When the granularity of the information in MML is not detailed (not subdivided), it is relatively difficult to achieve correct conversion. If the granularity on the MML side is relatively fine (divided), it is possible to store the information in the local database with tags added to it so that the volume of information is not lost, however this is not practical.

==== Granularity of documents

In general, each MML module item (MmlModuleItem, MML basic structure) can contain only one content, and each content can carry only one MML module. Therefore, each module item can be recognized as a single document. However, the granularity of documents should be defined for each document type.

[glossary]
Patient information::
Patient information is cumulative. In most cases, only the latest information is active one. Therefore, multiple patient information documents are not simultaneously active. Therefore, the granularity of the document is not a matter of concern.
Health insurance information::
A combination of available health insurance and public subsidy is considered to be one document. For details, refer to the explanation of the element.
Diagnosis record information::
Each diagnosis record is considered to be carried on each one document. Complications or secondary disease from the main disease are written in another documents. When the description of a disease name is divided into the main part with the modifier, the total parts are considered as one document. For details, refer to the explanation of the element.
Lifestyle information::
With regards to patient information module, multiple meaningful lifestyle information documents are not possible to be active and the granularity of the document is not a matter of concern.
Basic clinical information::
This is same as patient information module.
Initial-consultation-specific information::
This records are taken at one first visit (hospitalization), so this is considered to be a single document. However, the information may be acquired in stages and divided into several instances, when patients visit multiple medical providers. In such cases, the information should not be recorded in a single document.
Progress course information::
This module is used for recording a progress note. Each document should contain one description. Therefore, each document has only one author and is not possible to have plural authors. Usually, one description does not cover more than one date.
Surgery record information::
A series of events between entry and exit from  operation room are recorded be a single document module. When a patient exits from an operation room once and returns again to the operation room for surgery within a short period of time, such information should be described in two documents. Even if a surgeon, department in charge, or operation method changed during surgery, such surgical record should be recorded to a single document.
Clinical summary information::
Each summary document contains events in a period that a user subjected to record. For example, a discharge summary records one hospitalization episode. If a patient has been treated by multiple departments during hospitalization along with a change of the patient department, user can describe in both ways, whether the summary is divided or compiled into a single document.

==== parentIdによる文書間の関連付け

一つのモジュールアイテム（MML基本構造 MmlModuleItem）には，一つのユニークな文書ID（uid）が割り付けられる．uidはUUIDとする．uidは必須エレメントであり，MMLプロセッサーは，MMLインスタンス生成時に必ずuidを附番しなければならない．また，MMLプロセッサーは，MMLインスタンスを受け取った時に，何らかの手段でuidをローカルに保存しておくことを強く推奨する．

MMLでは，関連親文書ID（MML基本構造parentId）を記載し，文書をポイントすることにより，文書間の関連付けを行うことができる．

親文書IDによるポイントは，次のような利用法が考えられる．

==========================
. 文書の訂正（テーブルMML0008　 oldEdition） +
    すでに生成した文書を訂正，更新したい時に，前文書のuidをポイントする．ただし，前文書を物理的に消去する必要はなく，ユーザーインターフェイス上見えなくするに留めておくことが望ましい．
. オーダーとその結果の関連付け（テーブルMML0008　 order） +
    一つのオーダー文書を，複数の結果文書（通常どちらも経過記録情報モジュールを用いる）からポイントすることにより，検査結果のグルーピングが可能である．
    質問とその返答の関連付け（テーブルMML0008　 consult）
    電子メールのスレッド管理と同じ機能が可能である．
. 病名の変遷（テーブルMML0008　 originalDiagnosis）
    病名の時系列的な変遷を表すことが可能である．病名の終了（前病名文書と同じ病名で転記を終了とした新病名文書を生成），変化（前病名文書と異なる病名の新病名文書を生成），分離（前病名文書に対して，病名の異なる複数の新病名文書を生成），併合（複数の前病名文書に対して，一つの新病名文書を生成）を表すことができる．
. 病名に対する適用健康保険（テーブルMML0008　 healthInsurance）
    医事会計上必要である場合に，対応可能である．
==========================

TIP: MMLインスタンスを受け取るMMLプロセッサは，受け取ったMMLインスタンスの関連親文書IDから，該当する文書を検索できることが望ましい．しかし，受信側MMLプロセッサが検索できる保証がない場合は，送信側MMLプロセッサは，過去にすでに送った文書に対してのみ，親文書IDによるポイントを行うべきである．

==== groupIdによる文書間の関連付け
複数のモジュールを組み合わせて，要約や紹介状等を構築するためには，グループID （1.2.1.1.3.3. groupId）を用いる．モジュール単位で情報を管理する場合には，全く対等でまとまりのあるモジュール群は，同じ文書IDで管理されていた方が，検索抽出が容易であり，文書としてまとめる必要のある複数モジュールには，文書IDとは別個に，同じID（すなわちgroupId）を設定可能とする．

具体的には，MML文書ヘッダ（docInfo）内のdocIdの下位エレメントとして，uid（文書ユニークID），parentId（関連親文書ID）に続いて，groupIdエレメントを追加する．さらに，属性として，groupClassを置き，モジュール群の文書の種別（例えば紹介状）を設定可能とする．

==== データ型
MML Ver 4のデータ型はW3C XML Schema Ver 1.1に準拠する。具体的には以下の通りである。Ver 3までのtimePeriod型はxs:duration型で代用する。

[horizontal]
xs:string:: 文字列
xs:integer:: 整数
xs:decimal:: 10進数
xs:boolean:: 真偽値(true or false)
xs:date:: 日付型。ISO8601形式(CCYY-MM-DD)で表記する
xs:time:: 時刻型。ISO8601形式(hh:mmLss[Z\|(+\|-)hh:mm])で表記する
xs:dateTIme:: 日付時刻型。ISO8601形式(CCYY-MM-DDThh:mm:ss[Z\|(+\|-)hh:mm])で表記する
xs:duration:: 期間型。ISO8601形式に週（W)を加えたPnYnMnWnDTnHnMnS形式で表記する。
xs:token:: 空白置換と空白縮小が行われた文字列。


==== アクセス権と暗号化

MMLインスタンス生成者の判断により，一文書ごとにアクセス権を記載することができる（MML基本構造accessRight）．ただし，このアクセス権は，インスタンス生成時において，インスタンス生成者の判断により記載されるものであり，インスタンスを受ける側が，記載されたアクセス権をどのように利用するかは，MMLでは定義されない．すなわち，実際のアクセスコントロールは，ユーザーのアプリケーションに委ねられる．

MMLでは，インスタンスの暗号化を規定しない．暗号化の具体的な方法はユーザーによって選択される．しかし，暗号化情報エレメント（MML基本構造encryptInfo）に，暗号化に関する情報を記載することは可能である．記載方法は規定しない．

暗号化の想定される一つの方法として，MMLインスタンスの本文（MML基本構造MmlBody）のみを公開鍵方式により暗号化し，暗号化に関する情報（用いた暗号化方法）を暗号化情報エレメントに記載することが考えられる．生成者情報（MML基本構造mmlCi:CreatorInfo）の生成者ＩＤから生成者の公開鍵を取得し，復号できれば，電子署名となる．

MMLインスタンスの一部またはすべてを暗号化したものは，厳密にはMMLの規格外であり，復号されたもののみに対し，ＭＭＬの規格は適用される．


=== XHTMLの取り扱い
MMLでは，文章として記述すべき情報を多く含んでいるため，書式情報を交換しなければ，正確に意味が伝わらないことがある．よって，データ型がstringであるエレメントのいくつかには，XHTMLが使用できることを定義し、改行書式“<br/>”のみを必須の書式としてきた。他の要素は処理系依存であり、必ずしも処理する必要はないとしたが、XHTML部分に書式以外の情報が入る余地を残したことで、この部分にMMLでは規定していないさまざまな情報が構造化されて記載されて運用されることになった。

XHTML部分の扱いについてVer 4ではこれまで通りとするが、内容については精査しできる限り構造化して取り入れるように今後のバージョンで検討していくこととする。
