:Author: Shinji KOBAYASHI
:Email: skoba@moss.gr.jp
:toc: right
:toclevels: 2
:pagenums:
:sectnums: y
:sectnumlevels: 8
:sectoffset: 6
:imagesdir: ./figures
:linkcss:

== Basic policies

toc::[]

=== Version control of modules and namespace declaration
From this version 4 release, namespace declaration is separated with each version.

Before this release, the version of module was described at the end of namespace declaration.

For example, the following is the name space declaration of test history information module.

[source, xml]
----
 xmlns:mmlLb="http://www.medxml.net/MML/ContentModule/test/1.0"
----
This declaration shows that the version of laboratory test history module is 1.0, even if this modules was involved in either version MML Ver 3.0 or version MML Ver 2.3.

To clarify the version of MML, the version of MML is described after the URL of MedXML consortium as following.
[source, xml]
-----
 xmlns:mml="http://www.medxml.net/MML/v4"
-----

Version of each module is described the end of URL. This version will be changed after updates of module schema.

[source, xml]
-----
 xmlns:mmlLb="http://www.medxml.net/MML/v4/ContentModule/test/1.0"
-----
The modules and namespace declarations that are used with MML Version 4.0 are the following.

Structure module of MmlHeader and docInfo::
	xmlns:mml ="http://www.medxml.net/MML/v4/base/1.0"
Patient information module::
	xmlns:mmlPi ="http://www.medxml.net/MML/v4/ContentModule/PatientInfo/1.0"
Health insurance information module::
	xmlns:mmlHi ="http://www.medxml.net/MML/v4/ContentModule/HealthInsurance/1.1"
Diagnosis record information module::
	xmlns:mmlRd ="http://www.medxml.net/MML/v4/ContentModule/RegisteredDiagnosis/1.0"
Lifestyle information module::
	xmlns:mmlLs ="http://www.medxml.net/MML/v4/ContentModule/Lifestyle/1.0"
Basic clinical information module::
	xmlns:mmlBc ="http://www.medxml.net/MML/v4/ContentModule/BaseClinic/1.0"
Initial-consultation specific information::
	xmlns:mmlFcl ="http://www.medxml.net/MML/v4/ContentModule/FirstClinic/1.0"
Progress course information module::
	xmlns:mmlPc ="http://www.medxml.net/MML/v4/ContentModule/ProgressCourse/1.0"
Surgery record information module::
	xmlns:mmlSg ="http://www.medxml.net/MML/v4/ContentModule/Surgery/1.0"
Clinical summary information module::
	xmlns:mmlSm ="http://www.medxml.net/MML/v4/ContentModule/Summary/1.0":
Test history information module::
	xmlns:mmlLb="http://www.medxml.net/MML/v4/ContentModule/Test/1.0"
Report information module::
	xmlns:mmlRp="http://www.medxml.net/MML/v4/ContentModule/Report/1.0"
Referral module::
	xmlns:mmlRe="http://www.medxml.net/MML/v4/ContentModule/Referral/1.0"
Vital signs module::
	xmlns:mmlVs="http://www.medxml.net/MML/v4/ContentModule/VitalSign/1.0"
Flow sheet module::
	xmlns:mmlFs="http://www.medxml.net/MML/v4/ContentModule/FlowSheet/1.0"
Prescription module::
	xmlns:mmlFs="http://www.medxml.net/MML/v4/ContentModule/Prescription/1.0"
Injection record module::
	xmlns:mmlFs="http://www.medxml.net/MML/v4/ContentModule/Injection/1.0"
Hemodialysis module::
	xmlns:mmlHd="http://www.medxml.net/MML/v4/ContentModule/Hemodialysis/1.0"

=== Data definitions of MML

==== Types and definitions of time
MML defines various types of time according to the granularity and its features. These are listed below.

Indicates the time when the MML instance was created. It is expected that this will be input automatically as a time stamp when the MML creation process is executed. Therefore in principle it is unrelated to the time of the information that is recorded in the MML instance. Even if the information dates from 10 years earlier, because the MML instance was created today, the time when the instance was created will be recorded.

.Time expression in MML
1 createDate (as an attribute of Mml in MML basic structure)::
Indicates the time when the MML instance was created. It is expected that this will be input automatically as a time stamp when the MML creation process is executed. Therefore it is does not indicate the time of the information recorded in the MML instance in principle. Even if the recorded dates in MML instance was from 10 years earlier and the MML instance was created today,  the createDate should be the time of today when the instance was created.
2 start (as an attribute of scopePeriod in MML basic structure)::
This is the start date of the period for all of the information recorded in the MML instance. When there are multiple MmlModuleItem, this should be the start date of the entire period which includes all of the MmlModuleItem.
3 end (as an attribute scopePeriod of in MML basic structure)::
This is the end date of the period for all of the information recorded in the MML instance. When there are multiple MmlModuleItem, this should be the end date of the entire period which includes all of the MmlModuleItem.
4 confirmDate (as an attribute of MML basic structure)::
This is the date when information in the content of this document was finally fixed. Ordinarily this corresponds to the date when the medical record was electronically recorded. A confirmation date should be the date the event occurred and was recorded in a document. If the document about the events that happened before some days, the confirmDate should be the date when the document was recorded. In an MML document, it should be confirmed in the document content to determine the accurate date when the event happened.  Although there are cases when an event date is explicitly recorded as an element in a document, there are also cases when it is necessary to judge from the context or other information. This is unavoidable due to the way of current medical records operation.
5 start(as an attribute of confirmDate, MML basic structure)::
If the description of a content shows information across multiple dates (for example a summary), this records the start date of the period covered with the described information in the document. Unlike scopePeriod in (2) above which is the period that covers the entire MML instance, this start means the start of period of the a MmlModuleItem.
6 end (as an attribute of confirmDate, MML basic structure)::
In the same way as above, if the description of a content shows information across multiple dates, this records the end date of the period of the a MmlModuleItem.
7 mmlHi:startDate (as an attribute of Health insurance information module)::
This is the date on which the health insurance was issued. Because this date is unrelated to medical events, it is not subject to (2), (3), (5), and (6) above.
8 mmlHi:expiredDate(as an attribute of Health insurance informationmodule )::
This is the health insurance expiration date. Because this date also is unrelated to medical events, it is not subject to (2), (3), (5), and (6) above.
mmlRd:startDate (as an attribute of Diagnosis record information module)::
This date is not the date when a patient got the disease at first. It is the start date for use in insurance claims, and because it is unrelated to medical events, it is not subject to (2), (3), (5), and (6) above.
9 mmlRd:endDate(as an attribute of Diagnosis record information module)::
This date is not the date when the disease was cured. It is the end date for use in insurance claims. Because it is unrelated to medical events, it is not subject to (2), (3), (5), and (6) above.
10 mmlRd:firstEncounterDate(as an attribute of Diagnosis record information module)::
This is the first visit date, and is the date of the first date to start health insurance record. Because this event is unrelated to the symptoms and treatment of the illness itself, this date is also not subject to (2), (3), (5), and (6) above.
11 mmlSg:date (Surgery record information)::
This is the date that surgical operation was performed (date of event occurrence). It is not the date that this module was recorded. It is recorded as a (4) confirmDate MML basic structure. Because there are cases when the recording is not completed on the surgery date, mmlSg:date and confirmDate may not always be the same.
12 mmlSm:start (Clinical summary information, mmlSm:serviceHistory attribute)::
This is the start date for the period covered by the summary. It is usually the same value as the start attribute of the confirmDate in MML basic structure.
13 mmlSm:end (Clinical summary information, mmlSm:serviceHistory attribute)::
This is the end date for the period covered by the summary. It is usually the same value as the end attribute of the confirmDate in MML basic structure.

==== Granularity of elements
Element granularity is a common issue. For example, patient name is whether the patient name is unstructured and handled as a single element, or divided into elements such as last name and first name. As usual, it is preferable that information be prescribed using a fine-grain data model. However it is also necessary to consider that data will be collected by existing information systems. MML takes the step of allowing elements with different granularity to be selected, in order to prevent data degradation caused by mismatching granularity of data collected from different information systems.
Concrete examples are shown below.
==========================
. The address expression format: unstructured address (mmlAd:full) and tructured format (mmlAd:prefecture, mmlAd:city, mmlAd:town, mmlAd:homeNumber)
. The name expression format: unstructured name expression (mmlNm:fullname) and structured format (mmNm:family, mmlNm:given, mmlNm: middle)
. The diagnosis record information: unstructured diagnosis (mmlRd:diagnosis) and structured format (mmlRd:diagnosisContents)
. The initial-consultation-specific information: free text style expression (mmlFcl:freeNotes), and structured with time and event expressions (mmlFcl:pastHistoryItem)

. The progress course information: free text style expression (mmlPc:FreeExpression) and structured expression (mmlPc:structuredExpression)

. The subjective information in the progress course module: free text style expression (mmlPc:freeNotes), and structured by time and event expressions (mmlPc:subjectiveItem)

. The surgery record information, a full expression of a series of surgery procedures (mmlSg:operation) and separated elements expression (mmlSg:operationElement)
==========================
Even if an MML instance was generated accurately, the interchangeability between the MML instance and local database schema depends largely on the information granularity of the local database. If there was a mismatch in granularity, you should be careful in order to prevent data loss. When the granularity of the information in MML is not detailed (not subdivided), it is relatively difficult to achieve correct conversion. If the granularity on the MML side is relatively fine (divided), it is possible to store the information in the local database with tags added to it so that the volume of information is not lost, however this is not practical.

==== Granularity of documents

In general, each MML module item (MmlModuleItem, MML basic structure) can contain only one content, and each content can carry only one MML module. Therefore, each module item can be recognized as a single document. However, the granularity of documents should be defined for each document type.

[glossary]
Patient information::
Patient information is cumulative. In most cases, only the latest information is active one. Therefore, multiple patient information documents are not simultaneously active. Therefore, the granularity of the document is not a matter of concern.
Health insurance information::
A combination of available health insurance and public subsidy is considered to be one document. For details, refer to the explanation of the element.
Diagnosis record information::
Each diagnosis record is considered to be carried on each one document. Complications or secondary disease from the main disease are written in another documents. When the description of a disease name is divided into the main part with the modifier, the total parts are considered as one document. For details, refer to the explanation of the element.
Lifestyle information::
With regards to patient information module, multiple meaningful lifestyle information documents are not possible to be active and the granularity of the document is not a matter of concern.
Basic clinical information::
This is same as patient information module.
Initial-consultation-specific information::
This records are taken at one first visit (hospitalization), so this is considered to be a single document. However, the information may be acquired in stages and divided into several instances, when patients visit multiple medical providers. In such cases, the information should not be recorded in a single document.
Progress course information::
This module is used for recording a progress note. Each document should contain one description. Therefore, each document has only one author and is not possible to have plural authors. Usually, one description does not cover more than one date.
Surgery record information::
A series of events between entry and exit from  operation room are recorded be a single document module. When a patient exits from an operation room once and returns again to the operation room for surgery within a short period of time, such information should be described in two documents. Even if a surgeon, department in charge, or operation method changed during surgery, such surgical record should be recorded to a single document.
Clinical summary information::
Each summary document contains events in a period that a user subjected to record. For example, a discharge summary records one hospitalization episode. If a patient has been treated by multiple departments during hospitalization along with a change of the patient department, user can describe in both ways, whether the summary is divided or compiled into a single document.

==== Linkage of documents using the parentId
Each module item (MmlModuleItem, MML basic structure) must be assigned a unique document ID (uid). This uid should be UUID(Universally Unique IDentifier). "uid" is a required element and MML processor must assign uid at each time it generate an MML instance. In addition, an MML processor should record uid in local strage in anywaa, when it receives an MML instance.

MML syntax can associate a document to the parent document by specifying its document ID(parent ID in MML basic structure)., the related parent document ID (parentId, MML basic structure).

The following usage is available by specification with parent IDs:
==========================
Correction of document (Refer to table MML0008, oldEdition)::
When you correct or update a generated document, you only have to specify the uid of the previous document. It is not necessary to physically delete the previous document, but it is preferable that the previous document is invisible on the users' view.
Association an order with its result (Refer to table MML0008, order)::
Specifying one order document from multiple result documents (usually the progress course information module is used for both documents) allows grouping of test results. Threading control of email is available in the same way in order to associate query with its response (Refer to table MML0008, consult).
History of diagnosing process (Refer to table MML0008, originalDiagnosis)::
Time series of diagnoses may be expressed. This association indicates the followings: Resolution of diagnosis (to add a new diagnosis record with the previous disease name and its outcome marks end), change (to add a new diagnosis record and change diagnosis name from the before), division (to create multiple new diagnoses with different disease names from the previous diagnosis), and merge (creation of a new diagnosis from multiple previous diagnoses).
Available health insurance for diagnosis (Refer to table MML0008, healthInsurance)::
Applicable health insurance to diagnosis may be specified when required by medical accounting.
==========================

NOTE: It prefers that an MML processor is able to search applicable documents with related parent document IDs, when it receives MML instances. However, the MML processor should send MML instances with parent IDs which refer to the document sent ever, in case that receiver is not sure to be able to search by parent ID of documents.

==== Linking documents using the groupId
Group ID (1.2.1.1.3.3. groupId) makes compounded documents, such as summaries and referral letters by combination of multiple document modules. It is easier to query group modules with the same identifier, if the documents can be grouped with equivalent relation. In such case, group ID can be assigned other than their own document IDs.

For example, following uid(document unique ID) and parent ID(ID for parent document) elements, is added as a subordinate element to the docId element within MML document header(docInfo). Furthermore, group Class attribute is able to mark the category of documents of module groups(such as referral letter).

==== Data types
The MML Ver. 4 data type conforms to W3C XML Schema Ver 1.1. The following list shows the all of them. "timePeriod" type used in ver 3 or before was substituted by the xs:duration type.

[horizontal]
xs:string:: String(or text)
xs:integer:: Integer
xs:decimal:: Decimal numbers
xs:boolean:: Boolean(true or false)
xs:date:: Date type. Expressed in ISO8601 format(CCYY-MM-DD)
xs:time:: Time type. Expressed in ISO8601 format(hh:mmLss[Z\|(+\|-)hh:mm])
xs:dateTIme:: Date and time type. Expressed in ISO8601 format (CCYY-MM-DDThh:mm:ss[Z\|(+\|-)hh:mm])
xs:duration:: Durration/Period type. Expressed in ISO8601 format added Week(W), (PnYnMnWnDTnHnMnS)
xs:token:: Strings removed line feeds, carriage returns, tabs, leading and trailing spaces, and multiple spaces.

==== Access control and encryption
MML instance creators can control an access rights of each document by describing accessRigght attribute in MML basic structure in docInfo. However, these access rights are recorded based on a decision by the instance creator at the time when the instance is created, MML does not define how the recorded access rights are to be used by receivers. In other words, access control depends on user application implementation.

ML does not define instance encryption. How to encrypt is implemented by the user. However it is possible to record encryption in the encryption information element (encryptInfo, MML basic structure). Description format is not defined.

A presumed method of encryption is to encrypt only the body of the MML instance (MmlBody, MML basic structure) using a public key encryption system, and to record information related to the encryption (the encryption method used) in the encryption information element. If decryption is possible by acquiring the creators' public key from the creator ID in the creator information (mmlCi:CreatorInfo, MML basic structure), and then this is applicable for digital signature.

However, MML instance that is wholly or partially encrypted is outside of MML standards, and the MML standards apply only to the decrypted instance.

=== XHTMLの取り扱い
Because MML contains large amounts of information which should be recorded as text, the structure of document may not be accurately communicated without format information. Therefore for several elements with data type string, this defines that XHTML can be used and the format requires only the line break format <br />. Other elements are dependent on the processing system, and processing of them is not always necessary. However by leaving additional space for information other than the format in XHTML parts, it has become possible to structure and record in these parts a variety of information which is not defined in MML.

The handling of XHTML parts in Ver. 4 is the same as in previous versions, however for future versions, the contents will be carefully examined and consideration given to incorporating as much structuring of the contents as possible.
