Author: Shinji KOBAYASHI
:Email: skoba@moss.gr.jp
:toc: right
:toclevels: 2
:pagenums:
:numberd:
:sectnums:
:imagesdir: ./figures
:linkcss:

=== Referral module
==== Introduction
The referral letter is defined by mmlRe:ReferralModule. The elements of this module was not deeply nested, but flat style.

==== Overview
Referral module was designed for the data interexchange between hospitals and clinics. Referral is a brief summary of patient's histories of illness and therapies to take over the care, and issued by every health provider. In Japan, the format was determined by the rule of health insurance for reimbursement. This referral module fully covers the format of health insurance system in Japan.

Only this module includes patient information in the structure other than docInfo.

Clinical images, test results, prescription, etc. are supposed to use mmlCm:extRef as the external references out of the MML instance. If you unify all the data elements by XML form, Using other MML modules is the way to do it, by mmlRe:testResults and others. mmlPs:PrescriptionModule is an alternative for mmlRe:medication.

It is same to other modules, referral module use mmlCi:CreatorInfo to describe the document creator. The document creator should be corresponded to the coreator of the refarral in the real world. The facility and department of the doctor should be applied the mmlCm:Id format and mmlPsi:PersonalizedInfo module．

===== Namespaces declaration

The namespaces declaration of this module is the following.

[source, xml]
xmlns:mmlRe="http://www.medxml.net/MML/v4/ContentModule/Referral/1.0"

===== The specification of document header of this module
===== docInfo
Attribute "contentModuleType" should be "referral" on the MML0005 table.

===== title
The title should describe the content of the referral letter.

The "generationPuropose" attribute should be "consult" on the MML0007 table.

===== confirmDate
It is the date when the referral module instance was created.

===== mmlCi:CreatorInfo
The creator on the referral module is the author of the referral. The actual writer (mmlCi:CreatorInfo) is possible to differ from the person referred (mmlRe:referFrom).

===== extRefs
This element contains mmlCm:extRef in this mmlRe:ReferralModule, is repeatable as the number of outer links.

===== content
Each content has one referral module.

.List of the elements.
[options="header"]
|===
| |Elements|Attribute|Data types|Occurrence|TableId
|M21|mmlRe:ReferralModule| | | |
|M21.1.|mmlPi:PatientModule| | | |
|M21.2.|mmlRe:occupation| |string|?|
|M21.3.|mmlRe:referFrom| | | |
|M21.3.1|mmlPsi:PersonalizedInfo| | | |
|M21.4.|mmlRe:title| |string| |
|M21.5.|mmlRe:greeting| |string|?|
|M21.6.|mmlRe:chiefComplaints| |string| |
|M21.7.|mmlRe:clinicalDiagnosis| |string|?|
|M21.8.|mmlRe:pastHistory| |string|?|
|M21.8.1.|mmlCm:extRef| | |*|
|M21.9.|mmlRe:familyHistory| |string|?|
|M21.9.1.|mmlCm:extRef| | |*|
|M21.10.|mmlRe:presentIllness| |string| |
|M21.10.1.|mmlCm:extRef| | |*|
|M21.11.|mmlRe:testResults| |string|?|
|M21.11.1.|mmlCm:extRef| | |*|
|M21.12.|mmlSm:clinicalCourse| | |?|
|M21.13.|mmlRe:medication| |string|?|
|M21.13.1.|mmlPs:PrescriptionModule| |string|?|
|M21.13.2.|mmlInj:InjectionModule| |string|?|
|M21.13.3.|mmlCm:extRef| | |*|
|M21.14.|mmlRe:referPurpose| |string| |
|M21.15.|mmlRe:remarks| |string|?|
|M21.15.1.|mmlCm:extRef| | |*|
|M21.16.|mmlRe:referToFacility| | | |
|M21.16.1.|mmlFc:Facility| | | |
|M21.16.2.|mmlDp:Department| | |?|
|M21.17.|mmlRe:referToPerson| | |?|
|M21.17.1.|mmlPsi:PersonalizedInfo| | | |
|M21.18.|mmlRe:referToUnknownName| |string|?|
|===
Occurrences; blank: 1, ?: 0 or 1, +: more than 1, *: more than 0 +
  #REQUIRED: mandatory attribute, #IMPLIED: optional attribute

==== Elements in details
===== M21. mmlRe:ReferralModule
[horizontal]
Description:: Referral module. Each instance of this module contains single referral letter by the doctor.
Occurrence:: 1..1.

===== M21.1. mmlPi:PatientModule
[horizontal]
Description:: Patient information module, which contains name, address, telecoms, etc. Further information is available in mmlPi:PatientModule description.
Occurrence:: 1..1.

===== M21.2. mmlRe:occupation
[horizontal]
Description:: Occupation.
Occurrence:: 0..1.
Data type:: string.
Layout:: XHTML available.

===== M21.3. mmlRe:referFrom
[horizontal]
Description:: Parent element to include the information of referrer.
Occurrence:: 1..1.

===== M21.3.1. mmlPsi:PersonalizedInfo
[horizontal]
Descrption:: The person who refer patient to, the schema was mmlPsi:PersonalizedInfo.
Occurence:: 1..1.

===== M21.4. mmlRe:title
[horizontal]
Description:: title of this instance, such as "Referral", or others.
Data type:: string.
Occurence:: 1..1.

==== M21.5. mmlRe:greeting
[horizontal]
Description:: the greeting of this referral letter.
Data type:: string.
Occurrence::  0..1.
Layout:: XHTML available.

.Example
[source, xml]
<mmlRe:greeting>
To whom it may concern,<xhtml:br/>
Mr Yoshihara is a xx years old male, who had injured his left leg.
...
Yours sincerely,
Shinji Kobayashi
</mmlRe:greeting>

===== M21.6. mmlRe:chiefComplaints
[horizontal]
Description:: Chief complaints.
Deta types:: string.
Occurrence:: 1..1.
Layout:: XHTML available.

===== M21.7. mmlRe:clinicalDiagnosis
[horizontal]
Description:: This element include unstructured diagnosis layouted by XHTML. If the diagnosis should be structured, mmlRd:RegisteredDiganosis module is available and the instance should be bundled by the same groupId.
Data type:: string.
Occurrence:: 0..1.
Layout:: XHTML available.

===== M21.8. mmlRe:pastHistory
[horizontal]
Description:: past history. mixed expression is allowable with mmlCm:extRef and text.
Data type:: string.
Occurrence:: 0..1.
Layout:: XHTML available.

===== M21.8.1. mmlCm:extRef
[horizontal]
Description:: external reference for the figures, such as graph. The structure is mmlCm:extRef.
Occurrence:: 0..*, repeatable as the nubmer of external reference files.

===== M21.9. mmlRe:familyHistory
[horizontal]
Description:: Family history, mixed expression is allowable with mmlCm:extRef and text.
Data type:: string.
Occurrence:: 0..1.
Layout:: XHTML available.

===== M21.9.1. mmlCm:extRef
[horizontal]
Description:: external referential figures, or tables. mmlCm:extRef structure is available.
Occurrence:: 0..*, repeatable as the number of external files to refer.

===== M21.10. mmlRe:presentIllness
[horizontal]
Description:: Present illness, mixed expression is allowable with mmlCm:extRef and text.
Data type:: string.
Occurrence: 1..1.
Layout:: XHTML available.

===== M21.10.1. mmlCm:extRef
[horizontal]
Description:: figures for external references. mmlCm:extRef format is available.
Occurence:: 0..*, repeatble as the number of files.

===== M21.11. mmlRe:testResults
[horizontal]
Description:: the results of the tests, mixed expression is allowable with mmlCm:extRef and text.
Data type:: string.
Occurrence:: 0..1.
Layout:: XHTML available.

===== M21.11.1. mmlCm:extRef
[horizontal]
Description:: external referential figures, or tables. mmlCm:extRef structure is available.
Occurrence:: 0..*, repeatable as the number of external files to refer.

===== M21.12. mmlSm:clinicalCourse
[horizontal]
Description:: Clinical course. The structure should refer to mmlSm:clinicalCourse(Clinical Summary module).
Data type:: string.
Occurrence:: 0..1.

===== M21.13. mmlRe:medication
[horizontal]
Description:: Active prescription. mixed expression is allowable with mmlCm:extRef and text.
Data type:: string.
Occurrence:: 0..1.
Layout:: XHTML available.

===== M21.13.1. mmlPs:PrescriptionModule
[horizontal]
Description:: The scheme should be referred to mmlPs:PrescriptionModule.
Occurrence:: 0..1.

.Example
[source, xml]
<mmlRe:medication>
  Prescription on discharge
  <mmlPs:PrescriptionModule>
    <mmlPs:medication>
      <mmlPs:batchNo>1</mmlPs:batchNo>
      <mmlPs:medicine>
        <mmlPs:name>Predonizone Tablet(5mg</mmlPs:name>
        <mmlPs:code mmlPs:system="YJ">61222033</mmlPs:code>
      </mmlPs:medicine>
      <mmlPs:dose>4</mmlPs:dose>
      <mmlPs:doseUnit>Tab</mmlPs:doseUnit>
      <mmlPs:frequencyPerDay>1</mmlPs:frequencyPerDay>
      <mmlPs:startDate>2015-05-13</mmlPs:startDate>
      <mmlPs:duration>P14D</mmlPs:duration>
      <mmlPs:instruction>p.o. before breakfast.</mmlPs:instruction>
    </mmlPs:medication>
  </mmlPs:PrescriptionModule>
</mmlRe:medication>

===== M21.13.2. mmlInj:InjectionModule
[horizontal]
Description:: the schema should be referred to mmlInj::InjectionModule参照
Occurrence:: 0..1.

===== M21.13.3. mmklupjlCm:extRef
[horizontal]
Description:: External references for files, tables, graphs, etc. The scheme should be refered to mmlCm:extRef.
Occurence:: 0..*, repeatable as the number of external files.

===== M21.14. mmlRe:referPurpose
[horizontal]
Description:: the purpose to refer.
Data type:: string
Occurence:: 1..1.
Layout:: XHTML available.

===== M21.15. mmlRe:remarks
[horizontal]
Descrption:: remarks, memorandum, mixed expression is allowebale with text and mmlCm:extRef.
Data type:: string.
Occurence:: 0..1.
Layout:: XHTML avalable.

===== M21.15.1. mmlCm:extRef
[horizontal]
Description:: External references for files, tables, graphs, etc. The scheme should be refered to mmlCm:extRef.
Occurence:: 0..*, repeatable as the number of external files.

===== M21.16. mmlRe:referToFacility
[horizontal]
Description:: the parent element to include the facility information to be referred to.
Occurence:: 1..1.

===== M21.16.1. mmlFc:Facility
[horizontal]
Description:: the facility to be referred to. THe schema should be follow the mmlFc:Facility.
Occurrence:: 1..1.

===== M21.16.2. mmlDp:Department
【内容】紹介先診療科．構造は MML 共通形式 (施設情報形式)mmlDp:Departmentを利用する． +
【省略】可

===== M21.17. mmlRe:referToPerson
【内容】紹介先医師名．氏名情報を入れる親エレメント． +
【省略】省略可

===== M21.17.1. mmlPsi:PersonalizedInfo
【内容】紹介先医師．構造はMML共通形式(個人情報形式)mmlPsi:PersonalizedInfoを利用する． +
【省略】不可

===== M21.18. mmlRe:referToUnknownName
【内容】医師名を指定しない相手． +
【データ型】string +
【省略】省略可
