MML 4.0
======

:Author: Shinji KOBAYASHI
:Email: skoba@moss.gr.jp

== はじめに

MMLは医療情報の交換規格として1995年より開発されてきた。当初はSGMLとして、version 2からはXMLを形式として採用し、臨床現場のユースケースに応じたモジュールの開発と、関連するテーブルの整備が行われてきた。2004年にはHL7 CDA rel1形式とのハーモナイズを行い、国際標準との相互運用性を向上させる試みが行われた。

2007年より次世代のEHR標準と期待されているISO 13606標準とのハーモナイズについての研究が行われ、その成果を元に2013年にバイタルサインモジュール、体温表モジュールが設計され、2015年には内服・外用処方モジュール、注射モジュールが公開された。

これらの成果ならびに透析SIGにおいて開発されてきた透析モジュールを加え、スキーマ定義言語をVer 3までのDTDからW3C XML Schema 1.1に変更してMML ver 4として改定し公開することとした。

== MML 4.0改定方針

前述の通り、今回の改定はW3C XML Schema 1.1に対応することが一番大きな改定である。XML Schemaはデータ型やデータ構造についての定義を細かく行うことができ、関連するツールも多様に存在することから開発者にとってより利便性が高まるよう意図している。

さらに、冗長であったHL7 CDA関連のタグ情報を排除することとし、構造を簡素化することとした。一方でNamespaceやタグ名は維持することとし、意味論的には等価でありxpath構造も維持することとし、バージョンアップに伴うコストを低減することとした。

さらにB案として検討されてきた下記のモジュールも正式に追加することとした。

. 透析モジュール
. バイタルサインモジュール
. 体温表モジュール
. 処方箋モジュール
. 注射モジュール

なお、MML 2.3で定義されていたData Exchange Specificationは廃止する。

== 知的所有権について
本仕様のすべての著作権は，特定非営利活動法人 MedXML コンソーシアムに帰属する．よって，その利用に当っては，以下の特定非営利活動法人 MedXML コンソーシアムのポリシーに従うものとする。

.成果物に関する，特定非営利活動法人 MedXML コンソーシアムのポリシー
----
本法人によって作成された成果物は，原則としてインターネット上に公開し，パブリックドメインとして取り扱う．従って，会員，非会員にかかわらず成果物を利用し，営利，学術活動に利用することが出来る．ただし，その利用にあたっては著作権，優先権に配慮，製品，論文などで本法人の成果物を利用したことを明記し，本法人への報告を義務付けるものとする
----

include::references.adoc[]

include::overview.adoc[]
