= 基本方針

== モジュールのnamespace宣言とバージョン管理

モジュールのバージョンはnamespace宣言の末尾の数字で示される。たとえば、バイタルサインモジュールのnamespace宣言が

----
xmlns:mmlVs="http://www.medxml.net/MML/ContentModule/vitalsign/4.0"
----
であれば、このバイタルサインモジュールのバージョンは4.0である。

MMLインスタンスには複数のアイテムを組み合わせて用いることができるため、作成日や作成者の異なる複数のアイテムによりインスタンスが構成されることがある。そのためMMLインスタンス全体および各アイテムを生成したスキーマのバージョンを明示しておく必要がある。

MML Version 4.0で使用する各モジュールとnamespace宣言を以下に示す。

|==============================
|MmlHeader および docInfo構造モジュール|xmlns:mml ="http://www.medxml.net/MML/base/4.0"
|患者情報モジュール|xmlns:mmlPi ="http://www.medxml.net/MML/ContentModule/PatientInfo/4.0"
|健康保険情報モジュール|xmlns:mmlHi ="http://www.medxml.net/MML/ContentModule/HealthInsurance/4.0"
|診断履歴情報モジュール|xmlns:mmlRd ="http://www.medxml.net/MML/ContentModule/RegisteredDiagnosis/4.0"
|生活習慣情報モジュール|xmlns:mmlLs ="http://www.medxml.net/MML/ContentModule/Lifestyle/4.0"
|基礎的診療情報モジュール|xmlns:mmlBc ="http://www.medxml.net/MML/ContentModule/BaseClinic/4.0"
|初診時特有情報モジュール|xmlns:mmlFcl ="http://www.medxml.net/MML/ContentModule/FirstClinic/4.0"
|経過記録情報モジュール|xmlns:mmlPc ="http://www.medxml.net/MML/ContentModule/ProgressCourse/4.0"
|手術記録情報モジュール|xmlns:mmlSg ="http://www.medxml.net/MML/ContentModule/Surgery/4.0"
|臨床サマリー情報モジュール|xmlns:mmlSm ="http://www.medxml.net/MML/ContentModule/Summary/4.0"
|検歴情報モジュール|xmlns:mmlLb="http://www.medxml.net/MML/ContentModule/Test/4.0"
|報告書情報モジュール|xmlns:mmlRp="http://www.medxml.net/MML/ContentModule/Report/4.0"
|紹介状モジュール|xmlns:mmlRe="http://www.medxml.net/MML/ContentModule/Referral/4.0"
|バイタルサインモジュール|xmlns:mmlVs="http://www.medxml.net/MML/ContentModule/VitalSign/4.0"
|体温表モジュール|xmlns:mmlFs="http://www.medxml.net/MML/ContentModule/FlowSheet/4.0"
|==============================

== MMLにおけるデータ定義

=== 時刻の種類と定義

MMLでは情報の粒度および性質に応じてさまざまな時刻が定義されている。以下にそれを列記する。

. createDate(MML基本構造 Mmlの属性) +
MMLインスタンスの生成時刻を示す。MMLの生成処理をする際にタイムスタンプとして自動的にに入力されることを想定している。したがって、MMLインスタンスに記載される内容の時刻とは原則として無関係であり、その内容が10年前であっても今日の時刻でMMLインスタンス化されたのであれば、生成された時点での時刻が記載される。

. start(MML基本構造 scopePeriodの属性) +
MMLインスタンス記載内容全体を通した期間の開始日である。MmlModuleItemが複数存在する場合ははすべてのMmlModuleItemを含めた期間とする。

. end(MML基本構造scopePeriodの属性) +
MMLインスタンス記載内容全体を通した期間の終了日である。MmlModuleItemが複数素材する場合はすべてのMmlModuleItemを含めた期間とする。

. confirmDate(MML基本構造) +
一つのcontentの記載内容が確定された日付である。通常は診療録が電子的に記録されて確定した日に相当する。記載確定日は、イベントが発生し文書が記載された日と一致することが運用上好ましい。しかしながら、運用上数日前のイベントを遅れて記載したような場合には、記載された日付をconfirmDateとして記録する。MMLではイベントが発生した正確な日付は文書内容を解析しなければわからない。文書内にエレメントとして明示的にイベント発生日時が記載されていることもあるが、文脈などから判断するしかない場合もある。これは、現在の診療録の運用上、やむを得ないことである。

. start(MML基本構造confirmDateの属性) +
contentの記載内容が複数の日付にまたがる情報(たとえばサマリー）である場合は記載内容が対象とする期間の開始日を記載する。上記(2)のscopePeriodがMMLインスタンス全体が対象期間であるのに対して、こちらは対応する一つのMmlModuleItemが対象期間である。

. end(MML基本構造cinfirmDateの属性) +
 上記同様にcontentの記載内容が複数の日付にまたがる情報であれば、対応する一つのMmlModuleItemが対象とする期間の終了日を記載する。

 . mmlHi:startDate(健康保健情報) +
 健康保険の交付年月日である。この日付は診療イベントと関係がないため上記(2)(3)(5)(6)の対象とはしない。
 . mmlHi:expiredDate(健康保健情報) +
 健康保険の有効期限である。この日付も診療イベントとは関係ないため、上記(2)(3)(5)(6)の対象とはしない。
 . mmlRd:startDate(診断履歴情報) +
 この日付は疾患の発症年月日ではなく、保険請求上の開始日であり診療イベントとは関係ないことが多いため、上記(2)(3)(5)(6)の対象とはしない。
 . mmlRd:endDate +
 この日付は疾患が治癒した日ではなく、保険請求上の終了日であり、診療イベントとは関係しないことが多いため、上記(2)(3)(5)(6)の対象とはしない。
 . mmlRd:firstEncounterDate(診断履歴情報)
 疾患の初診日であり、最初の保険医療行為の対象となった日である。疾患自体の発症や治癒と関係のないイベントであるため、この日付も上記(2)(3)(5)(6)の対象とはしない。
 . mmlSg:date(手術記録情報) +
 手術施行日(イベント発生日)であり、記載日ではない。記載日は(4)MML基本構造のconfirmDateとして記録する。手術施行日に記載が完了しない場合もあるため、mmlSg:dateとconfirmDateは必ずしも一致しない。
 . mmlSm:start(臨床サマリー情報 mmlSm:serviceHistoryの属性) +
 サマリー対象期間の開始日である。通常はMML基本構造confirmDateのstart属性と同じ値となる。
 . mmlSm:end(臨床サマリー情報mmlSm:serviceHistoryの属性) +
 サマリー対象期間御終了日である。通常はMML基本構造confirmDateのend属性と同じ値となる。

== エレメント粒度

患者氏名を構造化せずに一つのエレメントとするか、姓・名などのエレメントに分割して取り扱うかといったエレメント粒度はしばしば問題となる。本来であれば、細粒度のデータモデルによって情報が規定されていることが望ましいが、既存の情報システムからデータを収集することも想定する必要もある。粒度の異なる情報システムからデータを収集する際のミスマッチによる情報劣化を抑制するために、MMLではいくつかのエレメントにおいて、粒度の異なるエレメントを選択できるように配慮している。具体例を以下に示す。

. 住所表現形式における非構造化住所（mmlAd:full）と構造化形式で示された住所（mmlAd:prefecture， mmlAd:city，mmlAd:town，mmlAd:homeNumber）

. 人名表現形式における非構造化名前表現（mmlNm:fullname）と構造化形式による名前表現（mmlNm:family，mmlNm:given，mmlNm:middle）

. 診断履歴情報における非構造化病名（mmlRd:diagnosis）と構造化病名形式（mmlRd:diagnosisContents）

. 初診時特有情報における自由文章表現（mmlFcl:freeNotes）と時間表現併用型記載（mmlFcl:pastHistoryItem）

. 経過記録情報における自由記載（mmlPc:FreeExpression）と構造化記載（mmlPc:structuredExpression）

. 経過記録情報－Subject情報における自由記載（mmlPc:freeNotes）と時間表現併用型記載（mmlPc:subjectiveItem）

. 手術記録情報における手術法一連表記（mmlSg:operation）と要素分割表記（mmlSg:operationElement）

ただし，MMLインスタンスを正確に生成できても、MMLインスタンスからローカルデータベースへの変換は、ローカルデータベースの情報粒度に大きく依存する。情報粒度のミスマッチが生じている場合は、情報の損失が起きないように配慮する必要がある．相対的に、MML側の粒度が荒い（分割されていない）場合は、正確な変換は困難である。相対的にMML側の粒度が細かい（分割されている）場合は、情報量を落とさないためにタグをつけたままローカルデータベースに落とすことも、考慮されるが、現実的ではない。

== 文書の粒度

一つのMMLモジュールアイテム(MML基本構造MmlModuleItem)には、一つのcontentしか記載されないのが原則であり、さらに一つのcontentには一つのMMLモジュールしか記載されない。
