<?xml version="1.0" encoding="UTF-8"?>
<!--  透析履歴情報モジュール　スキーマ  2022/03/31  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mmlHdh="http://www.medxml.net/MML/v4/ContentModule/HemodialysisHistory/1.0" xmlns:mmlFc="http://www.medxml.net/MML/v4/SharedComponent/Facility/1.0" xmlns:mmlPi="http://www.medxml.net/MML/v4/ContentModule/PatientInfo/1.0" xmlns:mmlCm="http://www.medxml.net/MML/v4/SharedComponent/Common/1.0" elementFormDefault="qualified" targetNamespace="http://www.medxml.net/MML/v4/ContentModule/HemodialysisHistory/1.0">
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Name/1.0" schemaLocation="name.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Address/1.0" schemaLocation="address.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Phone/1.0" schemaLocation="phone.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Facility/1.0" schemaLocation="facility.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/ContentModule/PatientInfo/1.0" schemaLocation="patientinfo.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Common/1.0" schemaLocation="common.xsd"/>

<xs:element name="HemodialysisHistoryModule">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdh:HemoDialysisHistory"/>
		</xs:sequence>
		<xs:attribute name="version" type="xs:string" use="required"/>
		<xs:attribute name="createDate" type="xs:dateTime" use="required"/>
	</xs:complexType>
</xs:element>		
<xs:element name="HemoDialysisHistory">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlFc:Facility"/>
			<xs:element minOccurs="0" maxOccurs="1" name="note" type="xs:string"/>
			<xs:element minOccurs="1" maxOccurs="unbounded" ref="mmlHdh:hdIntroduction"/>
			<xs:element minOccurs="1" maxOccurs="unbounded" ref="mmlHdh:vascularAccess"/>
		</xs:sequence>		
	</xs:complexType>
</xs:element>
<xs:element name="hdIntroduction">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdh:hdDiagnosis"/>
			<xs:element minOccurs="0" maxOccurs="1" name="hdIntroDate" type="xs:date"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlFc:Facility"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="hdDiagnosis">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="system" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="vascularAccess">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="dateMade" type="xs:date"/>
			<xs:element minOccurs="0" maxOccurs="1" name="dateFirstUse" type="xs:date"/>
			<xs:element minOccurs="0" maxOccurs="1" name="dateEnd" type="xs:date"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdh:location"/>
			<xs:element minOccurs="0" maxOccurs="1" name="note" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="vaStatus" type="xs:string" use="optional"/>
	</xs:complexType>
</xs:element>
<xs:element name="location">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="tableId" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
</xs:schema>
