<?xml version="1.0" encoding="UTF-8"?>
<!--  透析指示情報モジュール　スキーマ  2022/04/03  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mmlHdo="http://www.medxml.net/MML/v4/ContentModule/HemodialysisOrder/1.0" xmlns:mmlFc="http://www.medxml.net/MML/v4/SharedComponent/Facility/1.0" xmlns:mmlPi="http://www.medxml.net/MML/v4/ContentModule/PatientInfo/1.0" xmlns:mmlCm="http://www.medxml.net/MML/v4/SharedComponent/Common/1.0" elementFormDefault="qualified" targetNamespace="http://www.medxml.net/MML/v4/ContentModule/HemodialysisOrder/1.0">
<!-- 上記 Hemodialysis　はどのように変更をするのか。小林先生に尋ねる-->
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Name/1.0" schemaLocation="name.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Address/1.0" schemaLocation="address.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Phone/1.0" schemaLocation="phone.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Facility/1.0" schemaLocation="facility.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/ContentModule/PatientInfo/1.0" schemaLocation="patientinfo.xsd"/>
<xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Common/1.0" schemaLocation="common.xsd"/>

<xs:element name="HemodialysisOrderModule">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:HemoDialysisOrder"/>
		</xs:sequence>
		<xs:attribute name="version" type="xs:string" use="required"/>
		<xs:attribute name="createDate" type="xs:dateTime" use="required"/>
	</xs:complexType>
</xs:element>
<xs:element name="HemoDialysisOrder">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlFc:Facility"/>
			<xs:element minOccurs="0" maxOccurs="1" name="note" type="xs:string"/>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:HDOrders"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:hdDailyOrder"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="HDOrders">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:orderGroups"/>
		</xs:sequence>
		<xs:attribute name="orderStatus" type="xs:string" use="required"/>
		<xs:attribute name="dateOrdered" type="xs:date" use="optional"/>
		<xs:attribute name="dateEffective" type="xs:date" use="optional"/>
	</xs:complexType>
</xs:element>
<xs:element name="orderGroups">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:effectiveDays"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeShift"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:hdMethod"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:dryWeight"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:weightCorrection"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:bloodFlow"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:filter"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:dialysate"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:dialysateFlow"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:dialysateTemp"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:substitution"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:needle"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:medication"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:injection"/>
			<xs:element minOccurs="0" maxOccurs="1" name="note" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="effectiveDays">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="weekday" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="timeShift">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="tableId" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="hdMethod">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:hdMethodName"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdStart"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdEnd"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="hdMethodName">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="tableId" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="timeHdStart">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:duration">
				<xs:attribute name="timeDirection" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="timeHdEnd">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:duration">
				<xs:attribute name="timeDirection" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="dryWeight">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" use="required" default="kg"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="weightCorrection">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" use="required" default="kg"/>
				<xs:attribute name="cnote" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="bloodFlow">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:flowRate"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdStart"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdEnd"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="flowRate">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" use="required" default="ml/min"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="filter">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="type" type="xs:string" use="optional"/>
				<xs:attribute name="membraneArea" type="xs:decimal" use="optional"/>
				<xs:attribute name="unit" type="xs:string" use="optional" default="m2"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="dialysate">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:dialysateName"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdStart"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdEnd"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="dialysateName">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="type" type="xs:string" use="optional"/>
				<xs:attribute name="modification" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="dialysateFlow">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:dialysateFlowRate"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdStart"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdEnd"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="dialysateFlowRate">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="dialysateTemp">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:dialysateTempValue"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdStart"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdEnd"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="dialysateTempValue">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" default="C" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="substitution">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:substitutionName"/>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:substitutionValue"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdStart"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdEnd"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:intermittent"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="substitutionName">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="type" type="xs:string" use="optional"/>
				<xs:attribute name="modification" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="substitutionValue">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" use="required"/>
				<xs:attribute name="dilution" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="intermittent">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdStart"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdEnd"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:substitutionInterval"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:substitutionSpeed"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="substitutionInterval">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="unit" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="substitutionSpeed">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="unit" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>			
<xs:element name="needle">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="type" type="xs:string" use="optional"/>
				<xs:attribute name="position" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="medication">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:drugName"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:dose"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHd"/>
			<xs:element minOccurs="0" maxOccurs="1" name="note" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="drugName">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="type" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="dose">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="timeHd">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:duration">
				<xs:attribute name="timeDirection" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="injection">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:drugName"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:dose"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdStart"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdEnd"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:routeName"/>
			<xs:element minOccurs="0" maxOccurs="1" name="note" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="routeName">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="xs:string" use="optional"/>
				<xs:attribute name="tableId" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="hdDailyOrder">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeShift"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:hdMethod"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:targetWeight"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:targetUF"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:ufrPlan"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:weightCorrection"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:bloodFlow"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:filter"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:dialysate"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:dialysateFlow"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:dialysateTemp"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:substitution"/>			
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:needle"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:medication"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlHdo:injection"/>
			<xs:element minOccurs="0" maxOccurs="1" name="note" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="orderDateTime" type="xs:dateTime" use="optional"/>
		<xs:attribute name="dateEffective" type="xs:date" use="optional"/>
	</xs:complexType>
</xs:element>
<xs:element name="targetWeight">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" default="kg" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>

<xs:element name="targetUF">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" default="kg" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<xs:element name="ufrPlan">
	<xs:complexType>
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" ref="mmlHdo:ufRate"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdStart"/>
			<xs:element minOccurs="0" maxOccurs="1" ref="mmlHdo:timeHdEnd"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="ufRate">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unit" type="xs:string" default="kg/h"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
</xs:schema>